# Generated by Django 3.1.6 on 2021-02-04 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScubaDiveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_depth', models.DecimalField(decimal_places=3, max_digits=6)),
                ('time_bellow_surface', models.TimeField()),
                ('starting_ox_level', models.DecimalField(decimal_places=3, max_digits=6)),
                ('ending_ox_level', models.DecimalField(decimal_places=3, max_digits=6)),
                ('location', models.CharField(max_length=100)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('outside_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('water_temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
