# Generated by Django 3.1.6 on 2021-02-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba_dive_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scubadivedata',
            name='max_depth',
            field=models.FloatField(),
        ),
    ]
