# Generated by Django 3.1.6 on 2021-02-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scuba_dive_data', '0002_auto_20210204_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scubadivedata',
            name='ending_ox_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scubadivedata',
            name='outside_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scubadivedata',
            name='starting_ox_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='scubadivedata',
            name='water_temp',
            field=models.FloatField(),
        ),
    ]
